title: Awesome Fellows
theme: jekyll-theme-cayman
exclude: ["README.md", "LICENSE", "/profiles/_template.md"]
domain: de-data-lab.github.io
url: https://de-data-lab.github.io
baseurl: "/learning-git" # Repository name
